### ISSUE TITLE
Error Compiling Less Stylesheet

### ISSUE THREAD

**Issue by Jaballadares** [smockle/colorful-json#1]
Console Errors:

![screen shot 2015-04-28 at 11 25 30 pm](https://cloud.githubusercontent.com/assets/4951251/7385601/ebb01252-edfd-11e4-8fcc-6ec8e116cef5.png)

Really excited about this package! Let me know if I can provide any more useful information.

**Comment by smockle** [comment]
@Jaballadares Thank you for reporting this! Sincere apologies for my belated reply; I’d turned off automatic watching, not realizing that setting would affect my own repos. Are you still experiencing this issue? I’ll set aside time this weekend to figure this out.

**Comment by smockle** [comment]
@Jaballadares @s-ogawa-mediba @ArthurZ @keithgordon @madrus I believe this is fixed in colorful-json version 1.0.0. Could you please update and let me know if the issue persists? Thank you again for reporting this.

**Comment by Jaballadares** [comment]
@smockle It's fixed. Thanks again for the great plugin!
