### ISSUE TITLE
Deprecated selector in `colorful-json/styles/colorful-json.less`

### ISSUE THREAD

**Issue by vforge** [smockle/colorful-json#4]
In `colorful-json/styles/colorful-json.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .meta.structure.dictionary.json:not(.value) > .string.quoted.double.json,
atom-text-editor::shadow .meta.structure.dictionary.json:not(.value) > .string.quoted.double.json > .punctuation.definition.string.json` => `atom-text-editor.editor .syntax--meta.syntax--structure.syntax--dictionary.syntax--json:not(.value) > .syntax--string.syntax--quoted.syntax--double.syntax--json,
atom-text-editor.editor .syntax--meta.syntax--structure.syntax--dictionary.syntax--json:not(.value) > .syntax--string.syntax--quoted.syntax--double.syntax--json > .syntax--punctuation.syntax--definition.syntax--string.syntax--json`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by smockle** [comment]
Thanks for opening this issue @vforge! More details are in this Atom PR: https://github.com/atom/atom/pull/12903

**Comment by smockle** [comment]
Interestingly, the suggested replacement in Atom’s deprecation window misses the `:not(.value)` => `:not(.syntax--value)`

**Comment by smockle** [comment]
This should be fixed in version `1.1.0`

**Comment by vforge** [comment]
Working as a charm. Thanks for being quick!
